[project]
name = "aoc"
version = "0.1.0"
description = "AoC 2024"
requires-python = ">=3.12"
dependencies = [
    "aocd>=0.1",
    "ipdb>=0.13.13",
    "jupyter>=1.1.1",
    "numpy>=2.1.3",
    "scipy>=1.14.1",
]
