[project]
name = "aoc"
version = "0.1.0"
description = "AoC 2024"
requires-python = ">=3.12"
dependencies = [
    "advent-of-code-data[nb]>=2.0.4",
    "aocd[nb]>=0.1",
    "ipdb>=0.13.13",
    "joblib>=1.4.2",
    "jupyter>=1.1.1",
    "numpy>=2.1.3",
    "rich>=13.9.4",
    "scipy>=1.14.1",
]
